packages:
  - resources/packages/*

minimumReleaseAge: 0

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  vue-demi: true

patchedDependencies:
  is-core-module@2.16.2: resources/patches/is-core-module@2.16.2.patch
  modern-monaco@0.4.2: resources/patches/modern-monaco@0.4.2.patch
  tailwindcss@3.4.19: resources/patches/tailwindcss@3.4.19.patch
  vm-browserify@1.1.2: resources/patches/vm-browserify@1.1.2.patch

updateConfig:
  ignoreDependencies:
    - tailwindcss3
