<script setup lang="ts">
import { onBeforeRouteLeave } from "vue-router";
import { ref, onBeforeMount, provide, computed, watch } from "vue";
import type { NavigationMenuItem } from "@nuxt/ui";
import { type Entry, useVolumeStore } from "@/dashboard/stores/volume";
import { useWizard } from "@/dashboard/composables/useWizard";
import { __ } from "@wordpress/i18n";
import { useRouter } from "vue-router";
import { useSettingsStore } from "@/dashboard/stores/settings";
import { useFileAction } from "@/dashboard/composables/useFileAction";
import VersionRequirement from "@/dashboard/components/Wizard/VersionRequirement.vue";

const volumeStore = useVolumeStore();
const fileAction = useFileAction();
const wizard = useWizard();
const router = useRouter();
const settingsStore = useSettingsStore();

const theme = ref(wizard.getDefaultTheme());
provide("theme", theme);

const isWizardReady = ref(false);
const wizardEntry = computed(() =>
  volumeStore.data.entries.find(
    (entry: Entry) =>
      entry.relative_path === "wizard.css" && !entry.hidden && !entry.directory,
  ),
);
const wizardCssContent = computed(() => wizardEntry.value?.content);
let isApplyingCss = false;
let lastSyncedCssContent: string | undefined;

// Check if Tailwind CSS v4 is active
const isTailwindV4 = computed(() => {
  return Number(settingsStore.virtualOptions("general.tailwindcss.version", 4).value) === 4;
});

function parseWizardContent(content: string) {
  if (!content.includes("@theme")) {
    content += "\n@theme {\n\n}";
  }

  return wizard.parseWizardFile(content);
}

function findWizardEntry() {
  return volumeStore.data.entries.find(
    (entry: Entry) => entry.relative_path === "wizard.css",
  );
}

function setWizardCssContent(content: string) {
  // The content watcher uses this marker synchronously. Set it before the
  // reactive entry mutation so a Wizard-originated update cannot be parsed
  // back into the theme as an external edit.
  lastSyncedCssContent = content;

  const existingEntry = findWizardEntry();

  if (existingEntry) {
    existingEntry.content = content;
    existingEntry.hidden = false;
    existingEntry.directory = false;
  } else {
    volumeStore.data.entries.push({
      name: "wizard.css",
      relative_path: "wizard.css",
      content,
      handler: "internal",
    });
  }
}

function syncCssFromTheme() {
  const content = wizard.stringifyTheme(theme.value);

  if (!content) {
    return;
  }

  if (wizardCssContent.value !== content) {
    setWizardCssContent(content);
  } else {
    lastSyncedCssContent = content;
  }
}

function syncThemeFromCss(content: string) {
  isApplyingCss = true;

  try {
    theme.value = parseWizardContent(content);
    lastSyncedCssContent = content;
  } finally {
    isApplyingCss = false;
  }
}

// Keep manual edits made in the file editor reflected in the Wizard while it
// is mounted. Changes generated by the Wizard are ignored here through the
// lastSyncedCssContent guard to prevent a sync loop.
watch(
  wizardCssContent,
  (content) => {
    if (
      !isWizardReady.value ||
      content === undefined ||
      content === lastSyncedCssContent ||
      isApplyingCss
    ) {
      return;
    }

    syncThemeFromCss(content);
  },
  { flush: "sync" },
);

// Keep the volume entry current as the Wizard controls change. This makes
// both the explicit Save action and navigation save use the latest theme.
watch(
  theme,
  () => {
    if (!isWizardReady.value || isApplyingCss) {
      return;
    }

    syncCssFromTheme();
  },
  { deep: true, flush: "sync" },
);

onBeforeMount(async () => {
  await Promise.all([volumeStore.initPull(), settingsStore.initPull()]);

  // Only parse wizard.css when Tailwind CSS v4 is active
  if (isTailwindV4.value) {
    const content = wizardEntry.value?.content || "";
    syncThemeFromCss(content);
    isWizardReady.value = true;
  }
});

async function saveWizard() {
  syncCssFromTheme();
  await fileAction.save();
}

const links = ref<NavigationMenuItem[][]>([
  [
    {
      label: __("Namespaces", "windpress"),
      type: "label",
    },
    {
      label: __("Screens", "windpress"),
      icon: "lucide:monitor-smartphone",
      to: router.resolve({ name: "wizard.screens" }),
    },
    {
      label: __("Spacing", "windpress"),
      icon: "lucide:align-horizontal-space-around",
      to: router.resolve({ name: "wizard.spacing" }),
    },
    {
      label: __("Typography", "windpress"),
      icon: "lucide:a-large-small",
      to: router.resolve({ name: "wizard.typography" }),
    },
    {
      label: __("Colors", "windpress"),
      icon: "lucide:swatch-book",
      to: router.resolve({ name: "wizard.colors" }),
    },
  ],
  [
    {
      label: __("Theme Configuration", "windpress"),
      type: "label",
    },
    {
      label: __("Theme Settings", "windpress"),
      icon: "lucide:settings",
      to: router.resolve({ name: "wizard.theme" }),
    },
  ],
]);

onBeforeRouteLeave(async (_1, _2, next) => {
  // Save the theme when leaving the route if Tailwind v4 is active
  if (isTailwindV4.value) {
    await saveWizard();
  }
  next();
});
</script>

<template>
  <!-- Show version requirement when Tailwind v3 is active -->
  <VersionRequirement v-if="!isTailwindV4" />

  <!-- Show normal wizard interface when Tailwind v4 is active -->
  <template v-else>
    <UDashboardPanel
      id="wizard-1"
      :default-size="20"
      :min-size="15"
      :max-size="30"
      resizable
      class="min-h-[calc(100svh-var(--wp-admin--admin-bar--height))]"
    >
      <UDashboardNavbar :title="i18n.__('Wizard', 'windpress')" class="text-sm">
        <template #leading>
          <UDashboardSidebarCollapse />
        </template>
        <template #right>
          <UTooltip :text="i18n.__('Save the changes to wizard.css file', 'windpress')">
            <UButton
              icon="i-lucide-save"
              color="primary"
              variant="subtle"
              :disabled="!isWizardReady"
              @click="saveWizard"
            />
          </UTooltip>
        </template>
      </UDashboardNavbar>

      <UNavigationMenu :items="links[1]" orientation="vertical" class="my-2" />
      <UNavigationMenu :items="links[0]" orientation="vertical" />
      <!-- <UNavigationMenu :items="links[1]" orientation="vertical" class="mt-auto" /> -->
    </UDashboardPanel>

    <RouterView />
  </template>
</template>
